name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t kliengsaengt/focus-property-fe .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push kliengsaengt/focus-property-fe:latest
      - name: Connect rds
        run: docker run --rm -it postgres psql -h focus-property-fe-rds.crmyeocekssj.ap-southeast-1.rds.amazonaws.com -U postgres -W focus
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kliengsaengt/focus-property-fe:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container kliengsaengt/focus-property-fe 